### ISSUE TITLE
KC user pulldown 

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-ng-user-admin#3]
* Connect to keycloak and get the user data
* Enter user data into input/dropdown component
* Add ability for selected component to be available in a different component so that the 'add user' button can retrieve the user that was selected

**Comment by franTarkenton** [comment]
Completed with this commit:
https://github.com/bcgov/nr-ng-user-admin/commit/0d1aba02c8dda2e88dedaac823acd328a436f136

Forgot to create a branch... not fixing as the repo is in early days.  Subsequent commits will follow proper practices!
