### ISSUE TITLE
Create pulldown for Forest Client admin

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-ng-user-admin#5]
* API exists that serves out forest client data.
* Create a service that wraps the forest client data
* Enter forest client data into pulldown
* ensure selected user is accessible outside of the component

**Comment by franTarkenton** [comment]
Version 1 now complete:

* loads all the forest clients into memory
* after user types three characters matching forest clients are loaded to the DOM and made available for selection from the dropdown
* Long term, the forest clients should be loaded from the api after 3 characters are typed

PR that closes this ticket:
https://github.com/bcgov/nr-ng-user-admin/pull/15
